### ISSUE TITLE
OSS2 - Aufgabe Issue Tracker

### ISSUE THREAD

**Issue by sosterwalder** [MatthiasWinzeler/bfh-os2-toolchain#3]
- Einen Issue Tracker aufsetzen
- Erstellen eines Projektes im Issue Tracker
- Erfassen von Benutzern und Definieren von Rechten
- Einen Bug u. Change erfassen
- Eine Version erfassen, Bug und Change dieser zuweisen
- Autom. Release-Notes erfassen
- Installation eines Repos
- Konfig. des Repos
- Integration des Repos in den Issue Tracker

**Comment by MatthiasWinzeler** [comment]
- Einen Issue Tracker aufsetzen
- Erstellen eines Projektes im Issue Tracker

> A issue tracker is automatically included when creating a github project.
- Erfassen von Benutzern und Definieren von Rechten

> We defined our collaborators here: https://github.com/MatthiasWinzeler/bfh-os2-toolchain/settings/collaboration
- Einen Bug u. Change erfassen
- Eine Version erfassen, Bug und Change dieser zuweisen

> bug: https://github.com/MatthiasWinzeler/bfh-os2-toolchain/issues/4
> change: https://github.com/MatthiasWinzeler/bfh-os2-toolchain/issues/5
> are both assigned to version https://github.com/MatthiasWinzeler/bfh-os2-toolchain/issues?milestone=2&state=open
- Autom. Release-Notes erfassen

> https://github.com/MatthiasWinzeler/bfh-os2-toolchain/releases/tag/v0.2
- Installation eines Repos
- Konfig. des Repos
- Integration des Repos in den Issue Tracker

> The repository and issue tracker are automatically integrated on github, we can reference to issues in commit messages etc.:
> https://github.com/MatthiasWinzeler/bfh-os2-toolchain/commit/12e501bdbadefbb62e242c769b17430d51cf26bc
> further options:
> https://help.github.com/articles/closing-issues-via-commit-messages
> 
> Pull requests are also very powerful and well integrated:
> https://github.com/MatthiasWinzeler/bfh-os2-toolchain/pull/2
> https://help.github.com/articles/using-pull-requests
